
spring:
  application:
    name: employee_microservice

    # esto son las cosas basicas para la base de datos
    # el puerto por defecto de postgresql es 5432, as√≠ que si ve que es encesario lo cambia
  datasource:
    url: jdbc:postgresql://localhost:5433/employee_db
    username: user_db
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  hostOne: ${ORIGINONE}
  hostTwo: ${ORIGINTWO}
  hostThree: ${ORIGINTHREE}

